network:
  version: 2
  ethernets:
    enp5s0:
      addresses: [10.10.10.51/24]
      routes:
        - to: default
          via: 10.10.10.1
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
    enp6s0:
      addresses:
        - 203.0.113.1/30
        - 2001:db8:b::1/64
    enp7s0:
      addresses:
        - 198.51.100.65/28
        - 2001:db8:e::1/64
    lo:
      addresses:
        - 198.51.100.1/32
        - 2001:db8:a::1/128
