network:
  version: 2
  ethernets:
    enp5s0:
      addresses: [10.10.10.10/24]
      routes:
        - to: default
          via: 10.10.10.1
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
    enp6s0:
      addresses:
        - 198.51.100.66/28
        - 2001:db8:e::10/64
      routes:
        - to: 2001:db8:ffff::/48
          via: 2001:db8:e::1
        - to: 192.0.2.0/24
          via: 198.51.100.65
