network:
  version: 2
  ethernets:
    enp7s0:
      addresses:
        - 198.51.100.18/28
        - 2001:db8:d::2/64
      routes:
        - to: 203.0.113.0/30
          via: 198.51.100.17
        - to: 2001:db8:b::/64
          via: 2001:db8:d::1
