package scenarios

import (
	"context"
	"testing"
	"time"

	"github.com/lightwebinc/multicast-test/harness/driver"
	dockerdriver "github.com/lightwebinc/multicast-test/harness/driver/docker"
	"github.com/lightwebinc/multicast-test/harness/env"
	"github.com/lightwebinc/multicast-test/harness/metrics"
)

// Scenario 01 — Functional all-shards
//
// Mirrors scenarios/01-functional-all-shards/run.sh.
//
// Topology (5 containers on mcast-fabric fd10::/64):
//
//	proxy      fd10::2   — shard-proxy, shard_bits=2, site-local multicast
//	listener1  fd10::11  — no filters; expects ~all frames forwarded
//	listener2  fd10::12  — SHARD_INCLUDE=0,1 + SUBTREE_EXCLUDE (1/8 subtree); expects ~7/8 of received
//	listener3  fd10::13  — SUBTREE_INCLUDE (1/8 subtree only); expects ~1/8 of received
//	source     fd10::3   — subtx-gen, 1000 pps × 10s, 8 subtrees, seed multicast-lab-bsv
//
// Filter values from ansible/listener-hosts.yml (generated by subtx-gen -print-subtrees):
//
//	listener2 SUBTREE_EXCLUDE: 336827e99b2caf22fcdda437828644c51cf39ff7a840a7cd16ae75310a34392a
//	listener3 SUBTREE_INCLUDE: 4a3e3eedc730fc42c786f83e8244f54f54e833922d71cfb1b1cc5e53147c5ece
const (
	subtreeExcludeL2 = "336827e99b2caf22fcdda437828644c51cf39ff7a840a7cd16ae75310a34392a"
	subtreeIncludeL3 = "4a3e3eedc730fc42c786f83e8244f54f54e833922d71cfb1b1cc5e53147c5ece"
)

func TestScenario01_FunctionalAllShards(t *testing.T) {
	ctx := context.Background()

	e := env.New(t, dockerdriver.New())

	// --- Register nodes -------------------------------------------------------

	e.AddNode(driver.NodeConfig{
		Name:  "s01-proxy",
		Image: "shard-proxy:harness",
		IPv6:  "fd10::2",
		Env: map[string]string{
			"MULTICAST_IF":    "eth0",
			"UDP_LISTEN_PORT": "9000",
			"EGRESS_PORT":     "9001",
			"SHARD_BITS":      "2",
			"MC_SCOPE":        "site",
			"MC_GROUP_ID":     "0x000B",
			"METRICS_ADDR":    ":9100",
		},
		MetricsPort: 9100,
		Role:        driver.RoleProxy,
	})

	listenerBase := map[string]string{
		"MULTICAST_IF": "eth0",
		"LISTEN_PORT":  "9001",
		"SHARD_BITS":   "2",
		"MC_SCOPE":     "site",
		"MC_GROUP_ID":  "0x000B",
		"NUM_WORKERS":  "1",
		"EGRESS_ADDR":  "127.0.0.1:9100",
		"METRICS_ADDR": ":9200",
	}

	l1env := copyEnv(listenerBase)
	e.AddNode(driver.NodeConfig{
		Name:        "s01-listener1",
		Image:       "shard-listener:harness",
		IPv6:        "fd10::11",
		Env:         l1env,
		MetricsPort: 9200,
		Role:        driver.RoleListener,
	})

	l2env := copyEnv(listenerBase)
	l2env["SHARD_INCLUDE"] = "0,1"
	l2env["SUBTREE_EXCLUDE"] = subtreeExcludeL2
	e.AddNode(driver.NodeConfig{
		Name:        "s01-listener2",
		Image:       "shard-listener:harness",
		IPv6:        "fd10::12",
		Env:         l2env,
		MetricsPort: 9200,
		Role:        driver.RoleListener,
	})

	l3env := copyEnv(listenerBase)
	l3env["SUBTREE_INCLUDE"] = subtreeIncludeL3
	e.AddNode(driver.NodeConfig{
		Name:        "s01-listener3",
		Image:       "shard-listener:harness",
		IPv6:        "fd10::13",
		Env:         l3env,
		MetricsPort: 9200,
		Role:        driver.RoleListener,
	})

	// Start proxy and listeners; source is started separately after MLD settle.
	e.StartAll(ctx)

	// --- MLD group-join settle ------------------------------------------------
	e.Sleep(4*time.Second, "MLD querier settle + multicast group joins")

	// --- Snapshot before ------------------------------------------------------
	urlL1 := e.MetricsURL(ctx, "s01-listener1")
	urlL2 := e.MetricsURL(ctx, "s01-listener2")
	urlL3 := e.MetricsURL(ctx, "s01-listener3")

	beforeL1 := e.Snapshot(ctx, "s01-listener1")
	beforeL2 := e.Snapshot(ctx, "s01-listener2")
	beforeL3 := e.Snapshot(ctx, "s01-listener3")

	// --- Start generator ------------------------------------------------------
	// Cmd contains only flags; the ENTRYPOINT in the image is /subtx-gen.
	sourceCmd := []string{
		"-addr", "[fd10::2]:9000",
		"-shard-bits", "2",
		"-subtrees", "8",
		"-subtree-seed", "multicast-lab-bsv",
		"-pps", "1000",
		"-duration", "10s",
		"-payload-size", "256",
		"-log-interval", "2s",
	}
	if err := dockerdriver.New().Start(ctx, driver.NodeConfig{
		Name:  "s01-source",
		Image: "subtx-generator:harness",
		IPv6:  "fd10::3",
		Cmd:   sourceCmd,
		Role:  driver.RoleGenerator,
	}); err != nil {
		t.Fatalf("start source: %v", err)
	}
	t.Cleanup(func() {
		dockerdriver.New().Stop(context.Background(), "s01-source") //nolint:errcheck
	})

	// Wait for subtx-gen to finish (it exits after -duration).
	exitCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	code, err := dockerdriver.New().WaitExit(exitCtx, "s01-source")
	if err != nil {
		t.Logf("source wait: %v", err)
	}
	t.Logf("source exited with code %d", code)

	// --- Egress pipeline drain ------------------------------------------------
	e.Sleep(2*time.Second, "egress pipeline drain")

	// --- Snapshot after -------------------------------------------------------
	afterL1 := metrics.ScrapeOrFail(t, urlL1)
	afterL2 := metrics.ScrapeOrFail(t, urlL2)
	afterL3 := metrics.ScrapeOrFail(t, urlL3)

	// --- Log container output for context -------------------------------------
	e.LogContainerOutput(ctx, "s01-source")

	// --- Compute deltas -------------------------------------------------------
	deltaL1 := metrics.DeltaMap(beforeL1, afterL1)
	deltaL2 := metrics.DeltaMap(beforeL2, afterL2)
	deltaL3 := metrics.DeltaMap(beforeL3, afterL3)

	recvL1 := deltaL1["bsl_frames_received_total"]
	recvL2 := deltaL2["bsl_frames_received_total"]
	recvL3 := deltaL3["bsl_frames_received_total"]

	// Use received-dropped as "passed filter" — this is independent of egress
	// success. bsl_frames_forwarded_total only fires on a successful Send(),
	// which can be unreliable when EGRESS_ADDR has no listener (ICMP feedback
	// on connected UDP causes alternating ECONNREFUSED → ~50% success rate).
	dropL1 := deltaL1["bsl_frames_dropped_total"]
	dropL2 := deltaL2["bsl_frames_dropped_total"]
	dropL3 := deltaL3["bsl_frames_dropped_total"]

	passL1 := recvL1 - dropL1
	passL2 := recvL2 - dropL2
	passL3 := recvL3 - dropL3

	t.Logf("listener1: received=%.0f dropped=%.0f passed=%.0f", recvL1, dropL1, passL1)
	t.Logf("listener2: received=%.0f dropped=%.0f passed=%.0f", recvL2, dropL2, passL2)
	t.Logf("listener3: received=%.0f dropped=%.0f passed=%.0f", recvL3, dropL3, passL3)

	// --- Assert ---------------------------------------------------------------
	// listener1: no filter — all frames pass (±5%)
	metrics.AssertNear(t, "listener1 passed filter", passL1, recvL1, 0.05)

	// listener2: shards 0+1 only + exclude 1 of 8 subtrees → pass ≈ received × 7/8 (±10%)
	// (SHARD_INCLUDE=0,1 means listener2 already only receives shards 0+1 via
	// multicast join; SUBTREE_EXCLUDE filters 1 of 8 within that)
	metrics.AssertNear(t, "listener2 passed filter (subtree-exclude)", passL2, recvL2*7/8, 0.10)

	// listener3: include only 1 of 8 subtrees → pass ≈ received × 1/8 (±15%)
	metrics.AssertNear(t, "listener3 passed filter (subtree-include)", passL3, recvL3*1/8, 0.15)

	// Sanity: at least 5000 frames received on listener1 (generator sends ~9000).
	metrics.AssertGTE(t, "listener1 received > 5000", recvL1, 5000)
}

// copyEnv returns a shallow copy of m.
func copyEnv(m map[string]string) map[string]string {
	c := make(map[string]string, len(m))
	for k, v := range m {
		c[k] = v
	}
	return c
}
