all:
  children:
    bgp_routers:
      vars:
        ansible_user: ubuntu
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -o GSSAPIAuthentication=no
        bgp_daemon: frr
        bgp_hold_time: 90
        bgp_keepalive: 30

      hosts:
        router1:
          ansible_host: 10.10.10.51
          bgp_local_as: 65000
          bgp_router_id: "198.51.100.1"
          bgp_ebgp_peers:
            - peer_ip: "203.0.113.2"
              peer_as: 65001
              description: "router2"

        router2:
          ansible_host: 10.10.10.53
          bgp_local_as: 65001
          bgp_router_id: "198.51.100.3"
          bgp_ebgp_peers:
            - peer_ip: "203.0.113.1"
              peer_as: 65000
              description: "router1"
          bgp_ibgp_peers:
            - peer_ip: "198.51.100.18"
              description: "proxy-v4"
            - peer_ip: "2001:db8:d::2"
              description: "proxy-v6"
